# Generated by Django 5.0.4 on 2024-05-20 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_catalogitem_count_alter_catalogitem_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название группы"),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.AlterModelOptions(
            name="catalogitem",
            options={"ordering": ["name"], "verbose_name_plural": "Каталог вещей"},
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="to_buy",
            field=models.BooleanField(default=False, verbose_name="Нужно купить"),
        ),
        migrations.AlterField(
            model_name="catalogitem",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Дата публикации"
            ),
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="group",
            field=models.ManyToManyField(to="catalog.itemgroup"),
        ),
    ]
