# Generated by Django 5.0.4 on 2024-12-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_catalogitem_options_alter_itemgroup_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogitem",
            name="catalog_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.cataloggroup",
            ),
        ),
    ]
