# Generated by Django 5.0.4 on 2025-01-19 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_alter_catalogitem_catalog_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cataloggroup",
            options={"ordering": ["name"], "verbose_name_plural": "Каталоги"},
        ),
        migrations.AddField(
            model_name="catalogitem",
            name="slug",
            field=models.SlugField(default="-", verbose_name="slug"),
        ),
        migrations.AddField(
            model_name="itemgroup",
            name="slug",
            field=models.SlugField(default="-", verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="cataloggroup",
            name="owners",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
