# Generated by Django 5.0.4 on 2025-09-15 15:25

from django.db import migrations
from django.db.models import Count
import uuid

def fix_duplicates(apps, schema_editor):
    ItemGroup = apps.get_model('catalog', 'ItemGroup')
    duplicates = (
        ItemGroup.objects.values('title')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for duplicate in duplicates:
        items = ItemGroup.objects.filter(title=duplicate['title'])
        for i, item in enumerate(items):
            if i > 0:
                suffix = str(uuid.uuid4())[:8]
                item.title = f"{item.title}_{suffix}"
                item.slug = f"{item.slug}_{suffix}"
                item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_migrate_catalog_data'),
    ]

    operations = [
        migrations.RunPython(fix_duplicates),
    ]
